export const GET_FETCH_REQUESTED = 'GET_FETCH_REQUESTED';
export const GET_FETCH_SUCCESS = 'GET_FETCH_SUCCESS';
export const GET_FETCH_FAILED = 'GET_FETCH_FAILED';


export const DOWNLOADING_STATUS = 'DOWNLOADING_STATUS'

export const SET_PROGRESS = 'SET_PROGRESS'